apiVersion: v1
kind: ConfigMap
metadata:
  name: zeppelin-shiro-conf
data:
  shiro.ini: |
   [users]
   admin = password1, admin
   priyanka = password2, admin
   prajakta = password3, admin
   saurabh = password4, admin
   [main]
   sessionManager = org.apache.shiro.web.session.mgt.DefaultWebSessionManager
   cookie = org.apache.shiro.web.servlet.SimpleCookie
   cookie.name = JSESSIONID
   cookie.httpOnly = true
   sessionManager.sessionIdCookie = $cookie
   securityManager.sessionManager = $sessionManager
   # 86,400,000 milliseconds = 24 hour
   securityManager.sessionManager.globalSessionTimeout = 86400000
   shiro.loginUrl = /api/login
   [roles]
        admin = *
   [urls]
   /api/version = anon
   /api/cluster/address = anon
   /api/interpreter/setting/restart/** = authc
   /api/interpreter/** = authc, roles[admin]
   /api/notebook-repositories/** = authc, roles[admin]
   /api/configurations/** = authc, roles[admin]
   /api/credential/** = authc, roles[admin]
   /api/admin/** = authc, roles[admin]
   #/** = anon
   /** = authc

