apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeppelin-server-notebook-volume
  namespace: spark-operator
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-client
