apiVersion: v1
data:
  nginx.conf: |
    daemon off;
    worker_processes auto;
    events {
      worker_connections 1024;
    }
    http {
      map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
      }

      # first server block will be default. Proxy zeppelin server.
      server {
        listen 80;
        location / {
          proxy_pass http://localhost:8080;
          proxy_set_header Host $host;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          proxy_redirect http://localhost $scheme://zeppelin.bb.kiya.ai;
        }
      }

      # match request domain [port]-[service].[serviceDomain]
      # proxy extra service such as spark-ui
      server {
        listen 80;
        server_name "~(?<svc_port>[0-9]+)-(?<svc_name>[^.]*)\.(.*)";
        location / {
          resolver 127.0.0.1:53 ipv6=off;
          proxy_pass http://$svc_name.NAMESPACE.svc:$svc_port;
          proxy_set_header Host $host;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          proxy_redirect http://localhost $scheme://zeppelin.bb.kiya.ai;

          # redirect rule for spark ui. 302 redirect response misses port number of service domain
          proxy_redirect ~(http:[/]+[0-9]+[-][^-]+[-][^.]+)[^/]+(\/jobs.*) $1.zeppelin.bb.kiya.ai$2;
        }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nginx.conf":"daemon off;\nworker_processes auto;\nevents {\n  worker_connections 1024;\n}\nhttp {\n  map $http_upgrade $connection_upgrade {\n    default upgrade;\n    '' close;\n  }\n\n  # first server block will be default. Proxy zeppelin server.\n  server {\n    listen 80;\n    location / {\n      proxy_pass http://localhost:8080;\n      proxy_set_header Host $host;\n      proxy_http_version 1.1;\n      proxy_set_header Upgrade $http_upgrade;\n      proxy_set_header Connection $connection_upgrade;\n      proxy_redirect http://localhost $scheme://zeppelin.bb.kiya.ai;\n    }\n  }\n\n  # match request domain [port]-[service].[serviceDomain]\n  # proxy extra service such as spark-ui\n  server {\n    listen 80;\n    server_name \"~(?\u003csvc_port\u003e[0-9]+)-(?\u003csvc_name\u003e[^.]*)\\.(.*)\";\n    location / {\n      resolver 127.0.0.1:53 ipv6=off;\n      proxy_pass http://$svc_name.NAMESPACE.svc:$svc_port;\n      proxy_set_header Host $host;\n      proxy_http_version 1.1;\n      proxy_set_header Upgrade $http_upgrade;\n      proxy_set_header Connection $connection_upgrade;\n      proxy_redirect http://localhost $scheme://zeppelin.bb.kiya.ai;\n\n      # redirect rule for spark ui. 302 redirect response misses port number of service domain\n      proxy_redirect ~(http:[/]+[0-9]+[-][^-]+[-][^.]+)[^/]+(\\/jobs.*) $1.zeppelin.bb.kiya.ai$2;\n    }\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"zeppelin-server-conf","namespace":"default"}}
  creationTimestamp: "2023-03-14T17:48:08Z"
  name: zeppelin-server-conf
  namespace: default
  resourceVersion: "11691722"
  uid: 9a0b9716-bd6b-4f21-abea-073b37b50320
